amplication/plugins

plugins/auth-basic/src/index.ts, plugins/auth-jwt/src/index.ts
fix: https://github.com/amplication/amplication/issues/3898
=> fix auth folder dir

plugins/broker-kafka/package-lock.json, plugins/broker-kafka/package.json, plugins/broker-kafka/src/index.ts
closes #14 
This PR anchor the kafka versions
After this PR will merge we need to publish a new version and update the DSG
=> Update kafka versions

plugins/auth-basic/package-lock.json, plugins/auth-basic/package.json, plugins/auth-basic/static/auth/base/token.service.base.ts, plugins/auth-basic/static/tests/auth/token.service.spec.ts, plugins/auth-jwt/package-lock.json, plugins/auth-jwt/package.json, plugins/auth-jwt/static/auth/base/token.service.base.ts, plugins/auth-jwt/static/auth/jwt/base/jwt.strategy.base.ts, plugins/auth-jwt/static/tests/auth/token.service.spec.ts
This PR implementaion https://github.com/amplication/amplication/pull/3948 in the plugins.
=> fix: token implementaion

plugins/broker-kafka/package-lock.json, plugins/broker-kafka/package.json, plugins/broker-kafka/src/index.ts
This PR add the logic that add the KafkaModule to the resource AppModule
=> feat(kafka): add app-module logic

plugins/auth-basic/package-lock.json, plugins/auth-basic/package.json, plugins/auth-basic/static/tests/auth/token.service.spec.ts, plugins/auth-jwt/package-lock.json, plugins/auth-jwt/package.json, plugins/auth-jwt/static/auth/base/token.service.base.ts, plugins/auth-jwt/static/tests/auth/token.service.spec.ts
related issues: https://github.com/amplication/amplication/issues/3939 and https://github.com/amplication/amplication/issues/4201
=>  remove `ts-ignore` and fix import order 

plugins/plugin-template/.gitignore, plugins/plugin-template/README.md, plugins/plugin-template/src/constants.ts, plugins/plugin-template/src/index.ts, plugins/plugin-template/src/types.ts, plugins/plugin-template/static/static_example_file.js
add template plugin for creating plugins. we need to add @MoFoGo docs to README file
=> plugin template

plugins/auth-core/package-lock.json, plugins/auth-core/package.json, plugins/auth-core/src/index.ts
related to issue: #[4431](https://github.com/amplication/amplication/issues/4431)
=> fix(auth-core): add modules to createServerAuth and bump version

plugins/formatter-prettier/README.md
Fixes: https://github.com/amplication/amplication/issues/4451
Update readme with correct plugin name
=> docs(prettier): update readme

plugins/auth-core/package-lock.json, plugins/auth-core/package.json, plugins/auth-core/src/index.ts
Related issue: https://github.com/amplication/amplication/issues/5348
=> fix(auth-core): Resolver entityName fix

plugins/auth-core/package-lock.json, plugins/auth-core/package.json, plugins/auth-core/src/index.ts, plugins/auth-jwt/package.json
Fixes: https://github.com/amplication/amplication/issues/4972
Update the dependencies related to jwt to fix security vulnerability on the generated apps
=> chore(auth-core): fix jwt security vulnerabilities 

plugins/swagger-apibody/.gitignore, plugins/swagger-apibody/.npmignore, plugins/swagger-apibody/README.md, plugins/swagger-apibody/package-lock.json, plugins/swagger-apibody/package.json, plugins/swagger-apibody/src/index.ts, plugins/swagger-apibody/src/util/ast.ts, plugins/swagger-apibody/tsconfig.json, plugins/swagger-apibody/webpack.config.js
Closes: https://github.com/amplication/amplication/issues/4278
=> Add Description of Routes and Entity properties to the REST-API Documentation#4278

plugins/db-mongo/package-lock.json, plugins/db-mongo/package.json, plugins/db-mongo/src/index.ts
This pull request fix an error that #87 created
=> fix(mongo): remove `depends_on` from docker-compose

plugins/nestjs-nats/package-lock.json, plugins/nestjs-nats/package.json, plugins/nestjs-nats/src/index.ts
This pull request fix the https://github.com/amplication/amplication/issues/5825 bug on the NATS plugin
=> fix(NATS): this plugin fix wrong import of template file

.vscode/settings.json, plugins/auth-basic/tsconfig.json, plugins/auth-basic/webpack.config.js, plugins/auth-jwt/tsconfig.json, plugins/auth-jwt/webpack.config.js, plugins/broker-kafka/package.json, plugins/broker-kafka/tsconfig.json, plugins/broker-kafka/webpack.config.js, plugins/db-mongo/tsconfig.json, plugins/db-mongo/webpack.config.js, plugins/db-mysql/tsconfig.json, plugins/db-mysql/webpack.config.js, plugins/db-postgres/tsconfig.json, plugins/db-postgres/webpack.config.js, plugins/formatter-prettier/package.json, plugins/formatter-prettier/tsconfig.json, plugins/formatter-prettier/webpack.config.js, plugins/plugin-template/package-lock.json, plugins/plugin-template/package.json, plugins/plugin-template/tsconfig.json, plugins/plugin-template/webpack.config.js, tsconfig.base.json
Depends on #41 
Related to https://github.com/amplication/amplication/issues/4997
This PR increases consistency within the plugins consolidating their tsconfig.json based on the recommended node 16 https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#tsconfig-bases 
It also consolidate the webpack configurations
=> chore: increase consistency within plugins

.github/workflows/publish.yaml, plugins/deployment-helm-chart/.amplicationrc.json, plugins/deployment-helm-chart/package.json, plugins/deployment-helm-chart/src/index.ts
Fixes a bug for mono-repository users.
=> fix(deployment-helm-chart): set default root_directory to false and fix rootDirectory path

plugins/nestjs-nats/package-lock.json, plugins/nestjs-nats/package.json, plugins/nestjs-nats/src/templates/nats.module.factory.ts
This pull request fixs https://github.com/amplication/amplication/issues/5884 by changing the service name implementation.
=> fix(NATS): change the service name implementation

plugins/nestjs-nats/package-lock.json, plugins/nestjs-nats/package.json, plugins/nestjs-nats/src/templates/nats.module.factory.ts
This pull request removes an unused constant of `SERVICE_NAME`
=> fix(NATS): remove unused const

plugins/auth-core/src/static/auth/LoginArgs.ts
Fixes: https://github.com/amplication/amplication/issues/6315
Issue related to the upgrade of https://github.com/amplication/amplication/issues/5877
=> fix(auth): auth core LoginArgs generation to follow new class-validator requirements of v0.14.0

plugins/auth-basic/package-lock.json, plugins/auth-basic/package.json, plugins/auth-core/package-lock.json, plugins/auth-core/package.json, plugins/auth-jwt/package-lock.json, plugins/auth-jwt/package.json
=> fix(auth-plugins): update packages versions

plugins/formatter-prettier/.amplicationrc.json, plugins/formatter-prettier/.gitignore, plugins/formatter-prettier/package-lock.json, plugins/formatter-prettier/package.json, plugins/formatter-prettier/src/index.ts, plugins/formatter-prettier/src/static/.prettierignore, plugins/formatter-prettier/src/static/.prettierrc.json, plugins/formatter-prettier/src/tests/__snapshots__/afterCreateApp.spec.ts.snap, plugins/formatter-prettier/src/tests/afterCreateApp.spec.ts, plugins/formatter-prettier/src/types.ts, plugins/formatter-prettier/src/utils.ts, plugins/formatter-prettier/tsconfig.json, plugins/linter-eslint/src/constants.ts, plugins/linter-eslint/src/events/createApp.ts, plugins/linter-eslint/src/events/createPackageJson.ts, plugins/linter-eslint/src/static/client/.eslintrc, plugins/linter-eslint/src/static/server/.eslintrc, plugins/linter-eslint/src/types.ts
- Have added custom settings for prettier.
- Integrated eslint with prettier
- Added tests for prettier
closes amplication/amplication#6606
closes amplication/amplication#6709
=> feat: add settings functionality

plugins/formatter-prettier/.npmignore, plugins/linter-eslint/.npmignore, plugins/linter-eslint/src/events/createApp.ts, plugins/linter-eslint/src/static/client/.eslintrc, plugins/linter-eslint/src/static/server/.eslintrc, plugins/linter-eslint/src/tests/__snapshots__/createApp.spec.ts.snap
=> fix: resolve indentation problems in eslint plugin

plugins/cache-redis/.amplicationrc.json, plugins/cache-redis/src/index.ts, plugins/cache-redis/src/tests/beforeCreateServerAppModule.spec.ts, plugins/cache-redis/src/tests/beforeCreateServerDotEnv.spec.ts, plugins/cache-redis/src/types.ts
Resolves [#6782](https://github.com/amplication/amplication/issues/6782)
=> fix(cache-redis): use the config module to handle environment variables

plugins/observability-opentelemetry/package-lock.json, plugins/observability-opentelemetry/package.json, plugins/observability-opentelemetry/src/constants.ts, plugins/observability-opentelemetry/src/index.ts
Fixes: amplication/amplication#6881
=> fix(opentelemetry): docker compose issues

plugins/deployment-helm-chart/README.md
The additional word in the sentence if incorrect.
=> docs: grammar mistake

plugins/deployment-helm-chart/src/index.ts
Closes: https://github.com/amplication/amplication/issues/7070
=> fix(deployment-helm-chart): console message update

plugins/plugin-template/webpack.config.js
Fixes: amplication/amplication#7150
Updated the plugin template bundler configuration by replacing the externals.
Removed the dependency to `webpack-node-externals`
Files changed :
plugins/plugin-template/webpack.config.js
=> fix(plugin): updating the plugin-template in plugins folder

plugins/ci-github-actions/src/index.ts
Fixes: amplication/amplication[[#7071](https://github.com/amplication/amplication/issues/7071)]
Corrects the typo in GitHub Actions.
=> fix(plugins):GitHub Actions typo

.github/workflows/publish.yaml, plugins/broker-rabbitmq/package-lock.json, plugins/broker-rabbitmq/package.json, plugins/broker-rabbitmq/src/index.ts
Fixes: amplication/amplication#7236
=> feat(rabbitmq): add support for nestjs v10

plugins/broker-rabbitmq/src/index.ts, plugins/broker-rabbitmq/src/tests/beforeCreateServerPackageJson.spec.ts
Fixes: amplication/amplication#7236
=> fix(rabbitmq): type safety issue

plugins/broker-nats/package-lock.json, plugins/broker-nats/package.json, plugins/broker-nats/src/index.ts
Fixes: amplication/amplication#7349
=> fix(nats): service and controller were not rightly populated

plugins/broker-nats/package-lock.json, plugins/broker-nats/package.json, plugins/broker-nats/src/index.ts
Fixes: amplication/amplication#7349
=> fix(nats): missing nats dependency in  docker-compose.dev

plugins/broker-rabbitmq/package-lock.json, plugins/broker-rabbitmq/package.json
Relates to: amplication/amplication#7360
=> chore(rabbitmq): update version to 0.0.1 as it not 100% functional yet

plugins/deployment-github-actions-aws-ecs/package-lock.json, plugins/deployment-github-actions-aws-ecs/package.json, plugins/provisioning-terraform-aws-deployment-ecs/package-lock.json, plugins/provisioning-terraform-aws-deployment-ecs/package.json
Fixes: amplication/amplication#[issue-number]
=> chore(terraform-aws-deployment-ecs) update deps and version

plugins/provisioning-terraform-aws-database-rds/package.json, plugins/provisioning-terraform-aws-database-rds/src/static/postgres/rds-template.tf
Fixes: amplication/amplication-cluster-configuration#120
=> fix: change the database to be resource managed to avoid prisma startup error

plugins/auth-basic/package-lock.json, plugins/auth-basic/package.json, plugins/auth-basic/src/templates/auth.module.template.ts, plugins/auth-jwt/package-lock.json, plugins/auth-jwt/package.json, plugins/auth-jwt/src/static/constants.ts
Fixes: amplication/amplication#7414
=> refactor(auth-jwt): move jwt constants from DSG to plugin

plugins/auth-jwt/src/templates/jwt.strategy.template.spec.ts
Fixes: amplication/amplication#6859  amplication/amplication#7046
=> fix(plugins): jwt plugins issue that was causing generated code tese failed

.github/workflows/fork-to-branch.yaml
Fixes: https://github.com/amplication/amplication/issues/7424
=> chore: point to correct repository

plugins/plugin-template/package-lock.json
Fixes: amplication/amplication#7441
=> chore(template): add missing package-lock

plugins/cache-redis/src/index.ts, plugins/cache-redis/src/tests/beforeCreateServerAppModule.spec.ts, plugins/cache-redis/src/tests/beforeCreateServerDockerCompose.spec.ts, plugins/cache-redis/src/tests/beforeCreateServerDockerComposeDev.spec.ts, plugins/cache-redis/src/tests/beforeCreateServerDotEnv.spec.ts, plugins/cache-redis/src/types.ts, plugins/cache-redis/src/utils.ts
Fixes: amplication/amplication#7456
=> fix(cache-redis) fix build

.github/workflows/ci.yaml, .github/workflows/nx.template.yaml, .github/workflows/publish.template.yaml, nx.json
=> chore(workflows): ci workflow publish

.github/workflows/nx.template.yaml
Fixes: https://github.com/amplication/amplication/issues/7441
=> chore: switch to new nx affected command that works with the setup

.github/workflows/nx.template.yaml
=> fix(workflows): print affected

.github/workflows/ci.yaml, .github/workflows/publish.template.yaml
=> chore(workflows): use short sha when publishing beta version

.github/workflows/ci.yaml, .github/workflows/publish.template.yaml
=> fix(workflows): npm secret

.github/workflows/ci.yaml, plugins/cache-redis/package-lock.json, plugins/cache-redis/package.json, plugins/cache-redis/src/index.ts, plugins/cache-redis/src/tests/beforeCreateServerAppModule.spec.ts, plugins/cache-redis/src/tests/beforeCreateServerDockerCompose.spec.ts, plugins/cache-redis/src/tests/beforeCreateServerDockerComposeDev.spec.ts, plugins/cache-redis/src/tests/beforeCreateServerDotEnv.spec.ts, plugins/cache-redis/src/utils.ts
Fixes: https://github.com/amplication/amplication/issues/7464
=> Chore(cache-redis) publish after fix build

.github/workflows/publish.template.yaml
=> fix(workflows): make the pr-number required false

.github/workflows/ci.yaml, .github/workflows/publish.template.yaml
=> fix(workflows): clean up the publish job

plugins/linter-eslint/package-lock.json, plugins/linter-eslint/package.json
Fixes: https://github.com/amplication/amplication/issues/7467
=> chore(linter-eslint): bump version

plugins/secrets-manager-aws-secret-manager/src/index.ts, plugins/secrets-manager-aws-secret-manager/src/static/on_demand/providers/secrets/secretsManager.service.ts, plugins/secrets-manager-aws-secret-manager/src/static/startup/providers/secrets/secretsManager.service.ts, plugins/secrets-manager-aws-secret-manager/src/static/startup/providers/secrets/secretsManagerFactory.ts, plugins/secrets-manager-aws-secret-manager/src/utils.ts
Fixes: amplication/amplication#7500
=> fix(aws-secrets-manager): issue related to code generated with wrong types

.github/workflows/ci.yaml
Fixes: https://github.com/amplication/amplication/issues/7505
=> fix(workflows): plugin validator

plugins/secrets-manager-aws-secret-manager/package-lock.json, plugins/secrets-manager-aws-secret-manager/package.json
Fixes: amplication/amplication#7500
=> chore(aws-secrets-manager): bump version

.github/workflows/ci.yaml
Part of: https://github.com/amplication/amplication/issues/7505
=> fix(workflows): remove plugin validator form publish needs

.github/workflows/ci.yaml
Part of: https://github.com/amplication/amplication/issues/7505
=> fix(workflow): skip publish on pr when validation fails

plugins/secrets-manager-aws-secret-manager/package-lock.json, plugins/secrets-manager-aws-secret-manager/package.json, plugins/secrets-manager-aws-secret-manager/src/utils.ts
Fixes: amplication/amplication#7524
=> fix(aws-secrets-manager): user settings issue

.github/workflows/publish-on-comment.yaml
Part of: https://github.com/amplication/amplication/issues/7499
=> fix(workflows): checkout to head on commit publish

plugins/broker-kafka/package-lock.json, plugins/broker-kafka/package.json, plugins/broker-kafka/src/constants.ts, plugins/broker-kafka/src/index.ts
Fixes: https://github.com/amplication/amplication/issues/7654
=> fix(broker-kafka): docker-compose.yml generate docker service that doesn't connect to kafka

plugins/provisioning-terraform-gcp-core/package-lock.json, plugins/provisioning-terraform-gcp-core/package.json, plugins/provisioning-terraform-gcp-database-csql/package-lock.json, plugins/provisioning-terraform-gcp-database-csql/package.json
Fixes: amplication/amplication-cluster-configuration#123
=> chore: update the versions of the gcp terraform modules to an incremented non-existing version

plugins/logger-json/.amplicationrc.json, plugins/logger-json/README.md, plugins/logger-json/package-lock.json, plugins/logger-json/package.json, plugins/logger-json/src/index.ts, plugins/logger-json/src/templates/logger.config.ts
Fixes: amplication/amplication#7673
Fix logger json plugin issue that was preventing the generated app to start properly
=> fix(logger-json): log level issue 

.eslintignore, .nxignore
Added templates to eslintignore.
=> chore: add templates to .eslintignore

plugins/integration-openai/package-lock.json, plugins/integration-openai/package.json, plugins/integration-openai/src/static/providers/openai/openai.service.ts
Fixes: amplication/amplication#7766
Update dependency to openai SDK v4
=> feat(openai): migrate generated code to new openai SDK v4

plugins/transport-grpc/package-lock.json, plugins/transport-grpc/package.json, plugins/transport-grpc/src/core/create-base-grpc-controller.ts, plugins/transport-grpc/src/core/create-grpc-proto-file.ts, plugins/transport-grpc/src/core/create-method-id-action-entity-map.ts
Fixes: amplication/amplication#7795
fix proto file methods names.
=> fix(gRPC): fix proto file methods names

plugins/integration-openai/package-lock.json, plugins/integration-openai/package.json, plugins/integration-openai/src/constants.ts
Fixes: amplication/amplication#7833
Fix issue related to missing updated version of the openai sdk dependency in the generated code
=> fix(openai): missing updated dependency to openai sdk

plugins/observability-opentelemetry/package-lock.json, plugins/observability-opentelemetry/package.json, plugins/observability-opentelemetry/src/constants.ts, plugins/observability-opentelemetry/src/static/otel-config.yml, plugins/observability-opentelemetry/src/tests/__snapshots__/loadStaticFiles.spec.ts.snap, plugins/observability-opentelemetry/src/tests/createDockerCompose.spec.ts, plugins/observability-opentelemetry/src/tests/createDockerComposeDev.spec.ts
Fixes: amplication/amplication#8047
=> chore(plugins): update OTEL configuration for exporters

plugins/observability-opentelemetry/package-lock.json, plugins/observability-opentelemetry/package.json, plugins/observability-opentelemetry/src/constants.ts, plugins/observability-opentelemetry/src/tests/createDockerCompose.spec.ts, plugins/observability-opentelemetry/src/tests/createDockerComposeDev.spec.ts
Fixes: amplication/amplication#8047
=> fix(plugins): fix port collision in otel docker compose dev

plugins/observability-opentelemetry/package-lock.json, plugins/observability-opentelemetry/package.json, plugins/observability-opentelemetry/src/constants.ts, plugins/observability-opentelemetry/src/tests/createPackageJson.spec.ts
Fixes: amplication/amplication#8143
https://github.com/amplication/opentelemetry-nestjs/commit/200cabff645ccb73b529c770ebbffafc8a609865
Update the dep version
=> chore(otel): update dependencies

libs/auth-core/src/core/create-token-service-test.ts, libs/auth-core/src/core/create-token-service.ts, plugins/auth-saml/.amplicationrc.json, plugins/auth-saml/src/events/create-server-secrets-manager.ts, plugins/auth-saml/src/static/auth/saml/samlSecretFactory.ts, plugins/auth-saml/src/templates/auth.module.template.ts, plugins/auth-saml/src/types.ts
Fixes: https://github.com/amplication/private-issues/issues/109
Move saml secrets to secrets manager 
=> feat(saml): leverage secrets manager for saml configuration secrets

package-lock.json, plugins/auth-auth0/package.json, plugins/auth-auth0/src/utils/createAuthProperties.ts, plugins/auth-keycloak/package.json, plugins/auth-keycloak/src/utils/createAuthProperties.ts
Fixes: amplication/amplication#8172
=> chore(plugins): allow auth plugins to support auth entity that has a Password field type

package-lock.json, plugins/broker-rabbitmq/package.json
Fixes: amplication/amplication#[issue-number]
=> chore(rabbitmq): bump version

package-lock.json, plugins/devcontainer-github-codespaces/package.json, plugins/devcontainer-github-codespaces/project.json
Fixes: amplication/amplication#8421
Add support for codespaces plugin package publishing
=> chore(codespaces): add configuration for package publishing

.eslintrc.json, .github/workflows/nx.template.yaml, migrations.json, nx.json, package-lock.json, package.json, plugins/transport-grpc/package.json, plugins/transport-grpc/src/core/create-grpc-proto-file.ts
Fixes: amplication/amplication#8501
Update nx to v19 to improve ci performance and reliability
=> chore(deps): update nx to v19

package-lock.json, plugins/dotnet-broker-kafka/package.json, plugins/dotnet-broker-kafka/src/index.ts
Fixes: https://github.com/amplication/amplication/issues/8703
Fix  static files path:
=> fix(dotnet-broker-kafka): static files path

package-lock.json, plugins/dotnet-broker-kafka/package.json, plugins/dotnet-broker-kafka/src/core/create-message-broker-method.ts, plugins/dotnet-broker-kafka/src/index.ts
Fixes: amplication/amplication#8703
=> fix(dotnet-broker-kafka): await FileMap functions

package-lock.json, plugins/dotnet-broker-kafka/package.json, plugins/dotnet-broker-kafka/src/index.ts
Fixes: amplication/amplication#8703
=> fix(dotnet-kafka-plugin): await FileMap methods correctly (take 2)

package-lock.json, plugins/dotnet-auth-core-identity/package.json, plugins/dotnet-auth-core-identity/src/core/create-app-services.ts
Fixes: amplication/amplication#8840
=> fix(dotnet-auth-plugin): write to appBlocks and not to builderBlocks

package-lock.json, plugins/auth-keycloak/package.json, plugins/auth-keycloak/src/events/createApp.ts
Fixes: https://github.com/amplication/amplication/issues/8905
use modules.merge function.
=> fix(keycloak): use modules.merge function

package-lock.json, plugins/auth-auth0/package.json, plugins/auth-auth0/src/events/createApp.ts, plugins/auth-keycloak/src/events/createApp.ts
Fixes: https://github.com/amplication/amplication/issues/8905
use modules.merge function.
=> fix(auth-0): use modules.merge function

package-lock.json, plugins/auth-auth0/package.json, plugins/auth-auth0/src/core/create-jwt-strategy-base.ts, plugins/auth-auth0/src/core/create-jwt-strategy.ts, plugins/auth-auth0/src/templates/jwt.strategy.base.template.ts, plugins/auth-auth0/src/templates/jwt.strategy.template.ts, plugins/auth-auth0/src/tests/__snapshots__/createServerAuth.spec.ts.snap
Fixes: amplication/amplication#8912
=> fix(auth0): fix jwt templates to use the new method names on entities

package-lock.json, plugins/dotnet-auth-core-identity/package.json, plugins/dotnet-auth-core-identity/src/core/create-seed-development-data.ts
Fixes: https://github.com/amplication/private-issues/issues/234
=> fix(dotnet-auth-core-identity): fix seed script to only create the initial user once
